language: php

php:
  - 5.4
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - "mysql -e 'create database `phphub`;'"
  - composer install -n --prefer-source
  - php artisan migrate --seed -n
  - echo '{"frontend.scripts":["scripts.js"],"frontend.styles":["styles.css"]}' > asset_manifest.json
  - ./vendor/bin/codecept build

script:
  - ./vendor/bin/codecept run
